server/.gitignore
server/README.md
server/index.ts
server/package.json
server/tsconfig.json

Adds a backend base with a hello world program and basic instructions for running it. Windows & macOS users especially should verify that the instructions are correct and expand on them.
Related issues: #8 #9

Backend base

---

.github/workflows/pr-workflow.yml
.reuse/dep5
server/README.md
server/jest.config.js
server/package-lock.json
server/package.json
server/src/index.ts
server/test/index.test.ts
server/tsconfig.json

Set up unit test environment for backend

---

server/src/database/seeders/001-dummy-data.ts

Sets sequence generator start value back to 1 after running seed:down

set sequences to restart from 1 after seed:down

---

client/src/components/auth/Login.js
client/src/components/auth/Signup.js
client/src/components/auth/SignupForm.js
client/src/tests/Signup.test.js
server/src/controllers/auth.ts
server/src/database/migrations/00001-initial-migration.ts
server/src/database/models/user.ts
server/src/routes/login.ts
server/test/routes/auth.test.ts

This will probably also require some minor changes on the frontend side!

Update auth routes to match specification

---

server/src/controllers/attainable.ts
server/src/controllers/utils/courseInstance.ts
server/src/routes/attainable.ts
server/test/controllers/attainable.test.ts

I've started to change parts of the code to just say "attainment" rather than "attainable" now, but not everything because that may interfere with other developers' work.

Attainment deletion API

---

client/public/index.html
client/src/components/AddAssignmentsView.js
client/src/components/CourseView.js
client/src/components/FrontPage.js
client/src/components/InstanceSummaryView.js
client/src/components/auth/LoginForm.js
client/src/components/course-view/Assignments.js
client/src/components/course-view/FileLoadDialog.js
client/src/components/course-view/MenuButton.js
client/src/components/create-course-view/CreateCourseForm.js
client/src/components/edit-instance-view/EditInstanceForm.js
client/src/components/fetch-instances-view/FetchedInstances.js
client/src/components/front-page/CourseCard.js
client/src/components/front-page/CourseTableRow.js

Added ids and classNames when there were many options without clear separating id.
Please comment if need for more naming

Ids and some classNames to ease navigation in tests

---

client/src/components/CourseView.js
client/src/components/course-results-view/CourseResultTableToolbar.js
client/src/components/course-view/FileLoadDialog.js
client/src/services/grades.js
client/src/tests/CourseView.test.js
client/src/tests/FileLoadDialog.test.js

Connects import grades from file (css upload) dialog to backend.
- upload function checks response and in case of failure the dialog shows errors from server to the user
- added snack pack to inform the user about success/failure
- created own test file for the component and refactored one test from course view to it
@kiiamakir I didn't change anything about the returnImportedGrades. If something needs to be done, suggest in the review.

Connect csv to backend

---

server/src/controllers/attainable.ts
server/src/controllers/auth.ts
server/src/routes/attainable.ts
server/src/routes/auth.ts
server/src/routes/course.ts
server/src/routes/courseInstance.ts
server/src/routes/grades.ts
server/src/routes/index.ts
server/src/routes/sisu.ts
server/src/routes/user.ts

- Added missing parameter definitions
- Added cookie auth to all endpoints except login and signup, auth not yet implemented in the controllers
- References to commonly used components to avoid repeating information

Update/refactor swagger API documentation

---

client/package-lock.json
client/package.json
client/src/components/course-view/FileErrorDialog.js
client/src/components/course-view/FileLoadDialog.js
client/src/tests/FileLoadDialog.test.js
server/src/middleware/errorHandler.ts

#207 
Update frontend grade loading from file to list all CSV parsing related errors (server responses with codes 400, 409 and 422).

Display csv parsing errors from backend

---

client/src/App.js
client/src/components/auth/Login.js
client/src/components/auth/PrivateRoute.js
client/src/components/auth/Signup.js
client/src/components/auth/UserButton.js
client/src/tests/UserButton.test.js
robot-tests/common/keywords.robot
robot-tests/common/variables.robot
server/src/controllers/auth.ts
server/src/database/models/user.ts
server/src/middleware/errorHandler.ts
server/src/routes/auth.ts
server/test/controllers/auth.test.ts

closes #209 
When user is logged in displays their name on the appbar. Hidden if not logged in.

Display the logged in users name on the top appbar

---

server/src/middleware/errorHandler.ts

simplify controllerDispatcher

---

client/src/components/FrontPage.js
client/src/components/auth/Login.js
client/src/components/auth/PrivateRoute.js
client/src/components/auth/Signup.js
client/src/services/courses.js

Display users courses on main page

---

server/src/controllers/attainable.ts
server/src/controllers/auth.ts
server/src/controllers/course.ts
server/src/controllers/courseInstance.ts
server/src/controllers/grades.ts
server/src/controllers/user.ts
server/src/middleware/authorization.ts
server/src/routes/attainable.ts
server/src/routes/course.ts
server/src/routes/courseInstance.ts
server/src/routes/grades.ts
server/src/routes/sisu.ts
server/src/routes/user.ts
server/test/controllers/attainable.test.ts
server/test/controllers/auth.test.ts
server/test/controllers/course.test.ts
server/test/controllers/courseInstance.test.ts
server/test/controllers/grades.test.ts
server/test/controllers/sisu.test.ts
server/test/controllers/user.test.ts
server/test/functions/csvParsing.test.ts
server/test/util/getCookies.ts

Authorization with JWT required on all API endpoint (except signup and login).

Update authorization to API endpoints

---

.github/workflows/pr-workflow.yaml
.reuse/dep5
server/README.md
server/docker-compose.yaml
server/pgAdminSetup.json
server/pgAdminpass

Access development database with pgAdmin using web browser.
closes #234

add pgadmin to backend docker-compose

---

client/src/components/CreateCourseView.tsx
client/src/components/InstanceSummaryView.tsx
client/src/components/create-course-view/CreateCourseForm.tsx
client/src/tests/mock-data/mockCourses.tsx

Add/remove mockdata in frontend components/tests to match the new course/course instance model update

Fix few frontend mock data

---

server/mock-data/assessment_model.sql
server/mock-data/attainment.sql
server/mock-data/course_instances.sql
server/mock-data/course_translations.sql
server/mock-data/courses.sql
server/mock-data/teachers_in_charge.sql

Tried to follow a realistic scenario of the actual course structure. Also an alternative "Special project" assessment model.

Add mock data entries for C course

---

server/mock-data/assessment_model.sql
server/mock-data/attainment.sql
server/src/controllers/attainment.ts
server/src/controllers/utils/attainment.ts
server/src/routes/attainment.ts
server/test/controllers/attainment.test.ts

Get root attainment of an assessment model

---

server/src/controllers/assessmentModel.ts
server/src/controllers/courseInstance.ts
server/src/controllers/grades.ts
server/src/controllers/utils/user.ts
server/src/routes/grades.ts
server/test/controllers/assessmentModel.test.ts
server/test/controllers/courseInstance.test.ts
server/test/controllers/grades.test.ts
server/test/mock-data/misc.ts

Restrict all grading related API endpoints to admin and teacher in charge users.
related to #228

Restrict grade creation/add/export rights

---

server/src/controllers/attainment.ts
server/src/controllers/auth.ts
server/src/controllers/grades.ts
server/src/routes/attainment.ts
server/src/routes/auth.ts
server/src/routes/grades.ts
server/test/controllers/attainment.test.ts
server/test/controllers/auth.test.ts
server/test/controllers/grades.test.ts

Reorder routes and controllers according to method

---

server/.gitignore
server/package-lock.json
server/package.json
server/src/app.ts
server/src/configs/environment.ts
server/src/configs/winston.ts
server/src/database/index.ts
server/src/database/migrations/00001-initial-migration.ts
server/src/database/migrations/00002-add-indexes.ts
server/src/database/migrations/00003-add-constraints.ts
server/src/database/seeders/001-dummy-data.ts
server/src/middleware/errorHandler.ts
server/src/middleware/requestLogger.ts
server/src/server.ts

Provides a base for building logging system for Aalto Grades.
This implementation adds basic logging for incoming request and other logging needs (errors, info, debug, etc.).
Data is logged to terminal during execution, errors are also logged to separate file.
Later on, Winston [transports](https://github.com/winstonjs/winston/blob/master/docs/transports.md) should allow fairly painless integration with Aalto logging systems.
related to #247

Backend basic logging with Morgan and Winston

---

server/src/controllers/user.ts
server/src/routes/user.ts
server/test/controllers/user.test.ts

* User can only access their own courses
* Admins can access any users courses
related to #286

Limit who can access users course

---

client/src/App.tsx
client/src/components/CourseResultsView.tsx
client/src/components/CourseView.tsx
client/src/components/EditInstanceView.tsx
client/src/components/FetchInstancesView.tsx
client/src/components/FrontPage.tsx
client/src/components/NotFound.tsx
client/src/components/course-results-view/SisuExportDialog.tsx
client/src/tests/NotFound.test.tsx
server/src/controllers/utils/attainment.ts
server/test/controllers/attainment.test.ts

Instead of empty page, returns 404 page if any missing params or route does not exist.
Closes #380

Not found page

---

client/.eslintrc.json
client/src/components/CreateCourseView.tsx
client/src/components/EditAttainmentView.tsx
client/src/components/EditInstanceView.tsx
client/src/components/FetchInstancesView.tsx
client/src/components/auth/ExternalAuth.tsx
client/src/components/course-results-view/CourseResultTableToolbar.tsx
client/src/components/course-results-view/FileLoadDialog.tsx
client/src/components/course-view/Attainments.tsx
client/src/components/course-view/CourseDetails.tsx
client/src/components/edit-attainment-view/Attainment.tsx
client/src/components/edit-attainment-view/ConfirmationDialog.tsx
client/src/components/edit-attainment-view/LeafAttainment.tsx
client/src/components/edit-attainment-view/ParentAttainment.tsx
client/src/components/edit-attainment-view/SimpleDialog.tsx
client/src/components/edit-attainment-view/StringTextField.tsx
client/src/components/front-page/CourseTable.tsx
client/src/tests/CourseResultsView.test.tsx
client/src/tests/CreateCourse.test.tsx
client/src/tests/EditAttainmentView.test.tsx
client/src/tests/EditInstance.test.tsx
client/src/tests/FileLoadDialog.test.tsx
server/.eslintrc.json

Update buttons, rename organizer to organizing department

---

client/package.json
client/src/App.tsx
client/src/components/CourseView.tsx
client/src/components/EditAttainmentView.tsx
client/src/components/EditCourseView.tsx
client/src/components/FrontPage.tsx
client/src/components/course-view/Attainments.tsx
client/src/components/course-view/CourseDetails.tsx
client/src/hooks/api/course.ts
client/src/tests/EditCourseView.test.tsx
server/src/controllers/course.ts
server/src/controllers/utils/course.ts
server/src/routes/course.ts
server/test/controllers/course.test.ts

Edit course view

---

client/src/components/CourseResultsView.tsx
client/src/components/EditCourseView.tsx
client/src/components/EditInstanceView.tsx
client/src/components/course-results-view/FileLoadDialog.tsx
client/src/components/course-view/CreateAssessmentModelDialog.tsx
client/src/hooks/api/assessmentModel.ts
client/src/hooks/api/attainment.ts
client/src/hooks/api/auth.ts
client/src/hooks/api/course.ts
client/src/hooks/api/grade.ts
client/src/hooks/api/instance.ts
client/src/types/index.ts

Invalidate queries in mutations

---

client/src/components/course-results-view/CourseResultTableToolbar.tsx

update course results view layout

---

client/src/components/CourseView.tsx
client/src/components/course-view/CreateAssessmentModelDialog.tsx

Assessment model template

---

client/src/App.tsx
server/src/controllers/grades.ts
server/src/controllers/utils/attainment.ts
server/src/routes/grades.ts
server/src/routes/index.ts
server/test/controllers/grades.test.ts

Edit attainment API

---

.github/PULL_REQUEST_TEMPLATE.md
.reuse/dep5

Adds a basic pull request template, this is what it should look like.
Not much relevant here.
Closes #233

Add pull request template

---

docker-compose-from-images.yaml

Slight description to docker compose yaml at server to mount database directory from host system, to make the database persistent.

Mount persistent directory for database at server

---

server/package-lock.json
server/package.json
server/src/controllers/grades.ts
server/test/controllers/grades.test.ts

Return union instead of intersection
Closes #454

union of the students of an instance and list of student numbers

---

client/src/components/EditInstanceView.tsx
client/src/components/FetchInstancesView.tsx
client/src/components/edit-formula-dialog/EditFormulaDialog.tsx
server/mock-data/teachers_in_charge.sql

UI Updates/Fixes

---

server/src/controllers/grades.ts

Make sure sisu csv grade is integer by rounding (removing possible decimals)

fix rounding

---

server/src/app.ts
server/src/controllers/user.ts
server/src/controllers/utils/date.ts
server/src/controllers/utils/grades.ts
server/src/database/index.ts
server/src/formulas/index.ts
server/src/formulas/manual.ts
server/src/formulas/weightedAverage.ts
server/src/middleware/authorization.ts
server/src/middleware/errorHandler.ts
server/src/middleware/index.ts
server/src/middleware/requestLogger.ts
server/test/util/getCookies.ts

update code comments

---

server/src/controllers/attainment.ts

Remove the deleted attainment from parent attainment child params information.

update child params on delete

---

.gitignore
client/package-lock.json
client/package.json
client/src/App.tsx
client/src/components/CourseResultsView.tsx
client/src/components/course-results-view/CourseResultsTableToolbar.tsx

Fix: Sisu CSV dialog doesn't show the extra text about containing already downloaded grades until refreshing after the initial download

---

server/src/controllers/grades.ts
server/test/controllers/grades.test.ts

Use latest attainment grade date for sisu csv

---

client/src/App.tsx

Fixes #532
Moved from old theme system to CSS Variables Theme asbaf
#532

Move to the new CSS Variables Theme

---

client/src/components/course-results-view/CourseResultsTableRow.tsx
client/src/components/course-results-view/GradeOptionsDialog.tsx
client/src/utils/index.ts

Fixes #500
+ Coloring the cell, added an icon and tooltip in the table
+ Coloring the background of the row in dialog for multiple grades
Closes #500

Expired grades should be indicated in UI

---

client/package-lock.json
package-lock.json

Resolved vulnerabilities

---

.github/workflows/pr-workflow.yaml

Only for the server testing. But if it works we can expand it to the whole workflow.

Testing new self-hosted runner

---

.github/workflows/pr-workflow.yaml

It was taking a lot of time just compiling everything for doing a placeholder test.

- removed e2e test (was a placeholder)

---

client/src/components/EditAttainmentView.tsx
server/src/controllers/attainment.ts

Fixes some bugs that caused an error when trying to add new attainments to assessment models

Fix add attainment

---

client/package.json
client/src/App.tsx
client/vite.config.ts

fix vite base url
+ vite preview on port 3005
Fix routing error and add Vite preview on port 3005
Closes #562

Fix routing error and add Vite preview on port 3005

---

client/package-lock.json
server/package-lock.json
server/package.json
server/test/controllers/assessmentModel.test.ts
server/test/controllers/attainment.test.ts
server/test/controllers/auth.test.ts
server/test/controllers/course.test.ts
server/test/controllers/courseInstance.test.ts
server/test/controllers/formula.test.ts
server/test/controllers/general.test.ts
server/test/controllers/grades.test.ts
server/test/controllers/sisu.test.ts
server/test/controllers/user.test.ts
server/test/util/getCookies.ts

updated supertest

---

client/Dockerfile.prod

Add  backend url env variable to prod docker

add backend url env variables

---

client/src/App.tsx
client/src/components/auth/PrivateRoute.tsx
client/src/components/auth/UserButton.tsx

Fix problems with logging in and out. Refactor PrivateRoute.tsx. Remove leftover `{' '}` from App.tsx
\-
Closes #573 and #503

Fix login issues. Closes #573 and #503

---

server/src/controllers/auth.ts

Update user name with name given by idp on first login
Closes #597

fix idp login user name

---

server/src/formulas/manual.ts

Fix manual formula parameter validation

---

client/package-lock.json
client/package.json
client/src/components/Graph.tsx
client/src/components/graph/AdditionNode.tsx
client/src/components/graph/AttainmentNode.tsx
client/src/components/graph/AverageNode.tsx
client/src/components/graph/BaseNode.tsx
client/src/components/graph/GradeNode.tsx
client/src/components/graph/MaxNode.tsx
client/src/components/graph/MinPointsNode.tsx
client/src/components/graph/RequireNode.tsx
client/src/components/graph/StepperNode.tsx
client/src/components/graph/SubstituteNode.tsx
client/src/components/graph/createGraph.ts
client/src/components/graph/formatGraph.ts
client/src/components/graph/graphUtil.ts
client/src/context/GraphProvider.tsx

Improve functionality of the graph component.
-

Improve graph

---

README.md
server/README.md

Merge contribute guide docs into dev

Contribute guide docs

---

client/src/components/course-view/AttainmentsView.tsx

Attainment Table view

---

client/src/components/auth/PrivateRoute.tsx
common/types/index.ts
server/src/controllers/assessmentModel.ts
server/src/controllers/attainment.ts
server/src/controllers/finalGrades.ts
server/src/controllers/grades.ts
server/src/controllers/user.ts
server/src/controllers/utils/user.ts
server/src/middleware/authorization.ts
server/src/routes/assessmentModel.ts
server/src/routes/attainment.ts
server/src/routes/finalGrades.ts
server/src/routes/grades.ts
server/src/routes/user.ts

- Move authorization checks into middlewares. Closes #630
- Revert "fixing" calling self-info when not logged.

Move checks to middleware

---

client/src/components/course-view/AttainmentsView.tsx
client/src/components/course-view/NewAttainmentDialog.tsx
client/src/hooks/api/attainment.ts

Add editing attainments
Closes #607

Edit attainments

---

client/src/components/CourseResultsView.tsx
client/src/components/course-results-view/CourseResultsTable.tsx
client/src/components/course-results-view/CourseResultsTableToolbar.tsx
client/src/components/course-results-view/EditGradesDialog.tsx
client/src/components/course-results-view/GradeCell.tsx
client/src/components/course-results-view/UserGraphDialog.tsx
client/src/components/graph/Graph.tsx
client/src/context/GradesTableProvider.tsx
client/src/tests/CourseResultsView.test.tsx
client/src/tests/mock-data/mockFinalGrades.ts
client/src/tests/mock-data/mockGrades.ts
client/src/utils/index.ts
client/src/utils/table.ts
common/types/finalGrade.ts
common/types/grades.ts
server/src/controllers/finalGrades.ts
server/src/controllers/grades.ts

Add ability to change best grade select option
Closes #558

Add ability to change best grade select option

---

client/src/tests/mock-data/mockCourse.ts
client/src/tests/mock-data/mockGrades.ts
common/types/user.ts
server/.eslintrc.cjs
server/src/controllers/assessmentModel.ts
server/src/controllers/auth.ts
server/src/controllers/course.ts
server/src/controllers/grades.ts
server/src/controllers/utils/auth.ts
server/src/controllers/utils/course.ts
server/src/database/migrations/00004-add-comment-to-fgrade.ts
server/src/database/models/assessmentModel.ts
server/src/database/models/attainmentGrade.ts
server/src/database/models/course.ts
server/src/database/models/courseRole.ts
server/src/database/models/finalGrade.ts
server/src/database/models/user.ts
server/src/middleware/authorization.ts
server/test/controllers/course.test.ts
server/test/controllers/grades.test.ts

- Update db data types to match db state. (mostly set types as nullable)

Improve db data types in backend

---

client/src/components/course-results-view/CourseResultsTable.tsx
client/src/components/course-results-view/CourseResultsTableToolbar.tsx
client/src/components/course-results-view/EditGradesDialog.tsx
client/src/components/course-results-view/GradeCell.tsx
client/src/components/course-results-view/UserGraphDialog.tsx
client/src/components/front-page/users-view/UsersTable.tsx
client/src/context/GradesTableProvider.tsx
client/src/context/useTableContext.tsx
server/src/controllers/utils/saml.ts
server/src/server.ts

Fix eslint warnings

---

client/src/components/course-results-view/CalculateFinalGradesDialog.tsx
client/src/components/course-results-view/CourseResultsTableToolbar.tsx
client/src/components/course-results-view/SisuDownloadDialog.tsx
client/src/components/course-view/ModelsView.tsx
client/src/components/front-page/users-view/AddUserDialog.tsx
client/src/context/GradesTableProvider.tsx
server/test/controllers/attainment.test.ts
server/test/controllers/finalGrades.test.ts
server/test/controllers/grades.test.ts

- hide archived assessment models (in filter & in calculate final grades)
- show warning in calculate final grades if graph contains deleted or archived attainments
- Make archived models more clear in models view
- 'succesfully' -> 'successfully'

Minor improvements

---

client/src/components/course-results-view/PredictedGradeCell.tsx
client/src/components/shared/PrettyChip.tsx
client/src/context/GradesTableProvider.tsx
client/src/utils/table.ts

Fixes #654
&
removed sorting for multiple grades preview, doesn't make sense, right?

Grades Table should preview only the selected model

---

.github/workflows/dev-container-workflow.yaml
.github/workflows/dev-push-workflow.yaml
.github/workflows/main-container-workflow.yaml
.github/workflows/playwright-workflow.yaml
.github/workflows/pr-workflow.yaml
.yamllint.yaml

Fix workflow warnings

---

server/test/util/responses.ts

Small simplification of the `ResponseTests` class.
None relevant.
None.

Simplify ResponseTests

---

client/src/components/course-view/CreateAssessmentModelDialog.tsx
client/src/components/course-view/EditAssessmentModelDialog.tsx
client/src/components/course-view/ModelsView.tsx

- Add support for renaming models

Add renaming assessment models

---

client/src/components/course-results-view/CourseResultsTable.tsx
client/src/components/course-results-view/EditFinalGradesDialog.tsx
client/src/components/course-results-view/EditGradesDialog.tsx
client/src/components/course-results-view/FinalGradeCell.tsx
client/src/components/course-results-view/GradeCell.tsx
client/src/context/GradesTableProvider.tsx
client/src/hooks/api/finalGrade.ts
client/src/utils/index.ts
common/types/finalGrade.ts
server/docs/common.yaml
server/docs/finalGrades.yaml
server/docs/grades.yaml
server/src/controllers/finalGrades.ts
server/src/controllers/grades.ts
server/src/controllers/utils/finalGrade.ts
server/src/controllers/utils/grades.ts
server/src/database/migrations/00001-initial-migration.ts
server/src/database/migrations/00007-add-manual-final-grade.ts
server/src/database/models/finalGrade.ts
server/src/routes/finalGrades.ts
server/src/types/dbNewDataTypes.ts
server/test/controllers/finalGrades.test.ts
server/test/util/createData.ts

Add editing final grades

---

client/src/components/course-results-view/EditFinalGradesDialog.tsx
client/src/components/course-results-view/FinalGradeCell.tsx
client/src/context/GradesTableProvider.tsx
client/src/utils/index.ts
server/src/controllers/grades.ts
server/test/controllers/grades.test.ts

- Use best final grade instead of the latest one

Use best final grade instead of the latest one

---

server/docs/attainment.yaml
server/docs/course.yaml
server/mock-data/courses.sql
server/src/controllers/attainment.ts
server/src/controllers/course.ts
server/src/database/migrations/00009-add-course-code-unique.ts
server/test/controllers/course.test.ts

- Force unique course code
- Fix missing 409 from documentation
Closes #321

Force unique course code

---

client/src/components/course-results-view/CalculateFinalGradesDialog.tsx

- Show warning to the user when using latest grades to calculate the final grade
Closes #689

Add warning when using latest grades

---

client/src/components/course-results-view/CourseResultsTableToolbar.tsx
client/src/components/course-view/EditCourseView.tsx
client/src/components/front-page/CreateCourseDialog.tsx
server/src/controllers/course.ts
server/src/controllers/finalGrades.ts
server/test/controllers/course.test.ts
server/test/controllers/finalGrades.test.ts

Prevent invalid final grades

---

client/src/App.tsx
client/src/components/course-view/EditCourseView.tsx
client/src/components/course-view/SideMenu.tsx
client/src/components/front-page/CreateCourseDialog.tsx
server/src/controllers/course.ts
server/src/controllers/utils/course.ts
server/src/database/migrations/00010-remove-course-role-uniqueness.ts
server/src/database/models/courseRole.ts
server/src/routes/course.ts
server/test/controllers/course.test.ts

- Allow teacher to edit assistants
Closes #684

Allow teacher to edit assistants

---

client/src/components/course-results-view/CourseResultsTableToolbar.tsx
client/src/components/course-results-view/FinalGradeCell.tsx
client/src/components/course-results-view/PredictedGradeCell.tsx
client/src/utils/textFormat.ts
server/src/controllers/finalGrades.ts
server/src/controllers/grades.ts
server/test/controllers/finalGrades.test.ts
server/test/controllers/grades.test.ts

Add support for second national language grading scale

---

client/src/App.tsx
client/src/components/FrontPage.tsx
client/src/components/StudentsView.tsx
client/src/hooks/api/user.ts
common/types/course.ts
common/types/user.ts
server/docs/course.yaml
server/docs/user.yaml
server/src/controllers/grades.ts
server/src/controllers/user.ts
server/src/controllers/utils/user.ts
server/src/database/models/courseRole.ts
server/src/middleware/authorization.ts
server/src/routes/user.ts
server/test/controllers/user.test.ts
server/test/util/createData.ts

- Should student's student role be removed if all of their grades are removed?
Closes #724

View student grades

---

client/src/components/alerts/SaveConfirmDialog.tsx
client/src/components/course-view/ModelsView.tsx
client/src/components/graph/Graph.tsx

Warn teacher when they try to edit a model with final grades.
Closes #730

Warn teacher if editing model with final grades

---

server/src/controllers/aplus.ts
server/test/controllers/aplus.test.ts

Updates the A+ grade fetching endpoint to use the recently changed A+ API.
Not particularly relevant.
Fixes part of #668

A+ grade fetching update

---

client/src/hooks/api/auth.ts

Don't show warning if calling self info fails with 401
Closes #635

Don't show warning if calling self info fails with 401

---

client/src/App.tsx
client/src/components/ManageStudentsView.tsx
client/src/components/StudentsView.tsx
client/src/components/front-page/users-view/UsersView.tsx
client/src/hooks/api/grade.ts
client/src/hooks/api/user.ts
common/types/grades.ts
common/types/user.ts
server/docs/grades.yaml
server/docs/user.yaml
server/src/controllers/grades.ts
server/src/controllers/user.ts
server/src/database/migrations/00015-change-attainment-grade-constraint.ts
server/src/database/models/attainmentGrade.ts
server/src/routes/grades.ts
server/src/routes/user.ts
server/test/controllers/grades.test.ts
server/test/controllers/user.test.ts

Add ability for admins to see all, filter, and delete students
Closes #744

Add deleting student data

---

client/src/components/course-view/AplusImportDialog.tsx
client/src/components/course-view/UploadDialog.tsx
client/src/components/course-view/UploadDialogAplusImport.tsx
client/src/components/course-view/UploadDialogUpload.tsx
client/src/hooks/api/aplus.ts
server/src/controllers/aplus.ts

Adds functionality to the frontend to import grades from A+ and fixes a few bugs in the backend.

A+ import frontend

---

.gitignore
common-services.yaml
docker-compose-from-images-dev.yaml
docker-compose-from-images.yaml
reverse-proxy/Dockerfile
reverse-proxy/reverse-proxy.conf
server/dockerfiles/Dockerfile.prod.run
server/dockerfiles/Dockerfile.prod.run.dev
server/docs/logging.md
server/src/configs/environment.ts
server/src/controllers/auth.ts
server/src/controllers/utils/saml.ts
server/src/server.ts

Improve production

---

server/src/controllers/grades.ts
server/test/controllers/grades.test.ts

Updates the grade creation endpoint to check for existing grades for a student from an A+ grade source, if such grades exist, they will be updated instead of creating new ones.
None

One grade per A+ grade source and user

---

.github/workflows/dev-push-workflow.yaml
.github/workflows/pr-workflow.yaml
server/test/controllers/aplus.test.ts

Fixes backend workflows not being marked as failed when the tests fail.
None relevant.
Fixes #785

Fix backend test workflows

---

client/src/components/course-view/ViewAplusGradeSourcesDialog.tsx
common/types/aplus.ts
server/docs/aplus.yaml
server/src/controllers/aplus.ts
server/src/controllers/utils/aplus.ts

Shows the date of A+ sources in the frontend.
Closes #790

Show date of A+ sources in frontend

---

client/Dockerfile
client/Dockerfile.prod
client/package.json
client/src/components/Footer.tsx
client/tsconfig.json
client/vite-env.d.ts
client/vite.config.ts
docker-compose-from-images-dev.yaml
docker-compose-from-images.yaml
package.json
server/package.json

Shows the version number from the root's `package.json` in the frontend and simplifies some Docker Compose files
Closes #610

Display version number

---

.eslintrc.json
client/package-lock.json
client/package.json
client/src/components/StudentsView.tsx
client/src/components/course-results-view/CourseResultsTable.tsx
common/package-lock.json
common/package.json
common/util/calculateGraph.ts
e2e-tests/package-lock.json
e2e-tests/package.json
package-lock.json
server/package-lock.json
server/package.json
server/src/controllers/utils/saml.ts

- Update vulnerable xmldom version
- Update packages
- Remove unused packages

Fix xmldom warning

---

.github/workflows/playwright-workflow.yaml
client/public/locales/en/translation.json
client/public/locales/fi/translation.json
client/public/locales/sv/translation.json
client/src/App.tsx
client/src/components/auth/Login.tsx
client/src/components/auth/OtpAuthDialog.tsx
client/src/components/auth/ResetPasswordDialog.tsx
client/src/components/auth/UserButton.tsx
client/src/components/front-page/CreateCourseDialog.tsx
client/src/hooks/api/auth.ts
client/src/tests/Login.test.tsx
common/types/auth.ts
e2e-tests/tests/login.ts
server/docs/auth.yaml
server/src/configs/environment.ts
server/src/controllers/auth.ts
server/src/controllers/utils/auth.ts
server/src/database/migrations/00022-add-mfa-confirmed.ts
server/src/database/models/user.ts
server/src/routes/auth.ts
server/src/types/auth.ts
server/test/controllers/auth.test.ts
server/test/util/createData.ts
server/test/util/getCookies.ts

Improve mfa

---

client/src/components/Header.tsx
client/src/components/graph/Graph.tsx
e2e-tests/tests/admin.spec.ts
e2e-tests/tests/assistant.spec.ts
e2e-tests/tests/teacher.spec.ts

Fix e2e tests

---

client/index.html

Matomo head script

---

README.md

Small note about MFA in the dev environment.

Note about MFA in dev

---

.eslintrc.json
client/src/components/front-page/users/AddUserDialog.tsx
client/src/components/login/ExternalAuth.tsx
server/mock-data/users.sql
server/src/middleware/requestLogger.ts

- Add eslint rule to require a newline after imports
- Fix add user dialog not resetting properly
- Fix external auth redirect
- Update password hashes in seed
- Small refactoring

Small fixes

---

server/src/middleware/requestLogger.ts

Omits plaintext passwords from HTTP logs. If the request body is malformed, the password will still get logged, but how big of a concern is that? Technically speaking we can't stop the user from getting their password logged somehow in any case. We could also maybe log the hash of the password rather than omitting it entirely.
None relevant.
None.

Don't log plaintext passwords

---

client/public/locales/en/translation.json
client/public/locales/fi/translation.json
client/public/locales/sv/translation.json
client/src/components/course/CoursePartsView.tsx
client/src/components/course/course-parts-view/NewAplusCourseTasksDialog.tsx
client/src/hooks/api/courseTask.ts
client/src/hooks/useApi.ts
common/types/courseTask.ts
common/types/general.ts
common/types/graph.ts
server/docs/courseTask.yaml
server/src/controllers/courseTask.ts
server/src/controllers/utils/courseTask.ts
server/src/routes/courseTask.ts
server/test/controllers/coursePart.test.ts
server/test/controllers/courseTask.test.ts
server/test/util/createData.ts

Replaces the adding, editing, and deleting endpoints for course tasks with a generic "modification" endpoint for mass editing tasks.
strings to the best of my ability
Fixes #846 
Fixes #708

Course task bulk editing endpoint

---

server/docs/finalGrade.yaml
server/docs/taskGrade.yaml
server/src/controllers/aplus.ts
server/src/controllers/coursePart.ts
server/src/controllers/utils/taskGrade.ts
server/test/controllers/aplus.test.ts
server/test/controllers/coursePart.test.ts
server/test/controllers/finalGrade.test.ts
server/test/controllers/gradingModel.test.ts
server/test/controllers/taskGrade.test.ts
server/test/functions/latestDate.test.ts
server/test/util/createData.ts
server/test/util/general.ts

Fix backend tests

---

client/src/components/course/course-results-view/SisuDownloadDialog.tsx

Added course code, current date in format YYYYMMDD and the download option (all, unexported, exported) to the default name of Sisu CSV file

add course code, date and download option in sisu csv file name

---

client/public/locales/en/translation.json
client/public/locales/fi/translation.json
client/public/locales/sv/translation.json
client/src/hooks/api/axios.ts

Throw an error with proper message when request from axios returning 401 status code

Show users proper error message when jwt token expired

---

client/src/components/course/EditCourseView.tsx
server/src/controllers/course.ts

- Removing separate logic handling for user role that is not admin in the server side
- Update the checking logic to decide whether an input field should be disabled in the client side

Enable teachers owners to edit the courses

---

client/package-lock.json
client/src/components/app-container/Header.tsx
client/src/components/course/GradesView.tsx
client/src/components/course/SideMenu.tsx
client/src/components/front-page/CourseTable.tsx
package-lock.json
server/package-lock.json

Update dependencies and fixes UI title
Closes #916

Update dependencies and fix title clipping

---

e2e-tests/playwright.config.ts
e2e-tests/tests/auth.setup.ts
e2e-tests/tests/teacher.spec.ts

Update auth setup to enable full parallel testing
Update "Create grading model" test for teacher

enable full parallel e2e testing

---

client/public/support.html
client/vite.config.mts

Revise contact information for support and update CSS settings to eliminate warnings.

Update contact information and CSS settings

---

client/public/locales/en/translation.json
client/public/locales/fi/translation.json
client/public/locales/sv/translation.json
client/src/components/course/ModelsView.tsx
client/src/components/course/course-results-view/GradesTableToolbar.tsx
client/src/components/course/course-results-view/UserGraphDialog.tsx
client/src/components/course/course-results-view/table/EditGradesDialog.tsx
client/src/components/course/course-results-view/table/GradeCell.tsx
client/src/components/course/course-results-view/table/PredictedGradeCell.tsx
client/src/context/GradesTableProvider.tsx
client/src/utils/bestGrade.ts
client/src/utils/table.ts

- Change the default value for expiredOption to 'non_expired'
- Update grade expiration date checking by adding checking the course part expired date
- Modify relevant component to use the updated findBestGrade, findBestFinalGrade, and gradeIsExpired function

Update expiredOption and consider coursePart expired date in grade expiration

---

server/src/controllers/taskGrade.ts

Change the logic in server side so that expiry date of grade can be updated to be null

Fix error can not clear expiry date of grade

---

client/src/components/course/course-results-view/table/EditGradesDialog.tsx

- A grade is considered as edited only if any property of it is changed

modify the logic for detecting edited task grades

---

client/public/locales/en/translation.json
client/public/locales/fi/translation.json
client/public/locales/sv/translation.json
client/src/components/course/EditCourseView.tsx
client/src/components/front-page/CreateCourseDialog.tsx
client/src/types/index.ts
common/types/course.ts
common/types/user.ts
server/docs/course.yaml
server/docs/user.yaml
server/mock-data/course_role.sql
server/src/controllers/course.ts
server/src/controllers/user.ts
server/src/controllers/utils/course.ts
server/src/database/migrations/00008-add-course-role-expiry-date.ts
server/src/database/models/courseRole.ts
server/src/middleware/authorization.ts
server/src/types/dataTypes.ts
server/src/types/general.ts
server/test/controllers/course.test.ts

Expiry date for course assistant can be created or edited

enable creating and editing expiryDate for course assistant

---

client/package-lock.json
client/package.json
client/public/locales/en/translation.json
client/public/locales/fi/translation.json
client/public/locales/sv/translation.json
client/src/components/course/course-results-view/HistoryDialog.tsx
client/src/components/course/course-results-view/table/EditGradesDialog.tsx
client/src/components/course/course-results-view/table/GradeCell.tsx
client/src/context/GradesTableProvider.tsx
client/src/hooks/api/history.tsx
client/src/hooks/api/taskGrade.ts
client/translation-utils.ts
common/types/history.ts
common/types/index.ts
common/types/logs.ts
common/types/taskGrade.ts
package-lock.json
server/docs/taskGrade.yaml
server/src/controllers/taskGrade.ts
server/src/controllers/utils/history.ts
server/src/database/migrations/00001-initial-migration.ts
server/src/database/migrations/00007-store-task-grade-log.ts
server/src/database/models/taskGradeLog.ts
server/src/routes/taskGrade.ts
server/src/types/dataTypes.ts

History of changes to grades

---

client/package-lock.json
client/package.json
common/package-lock.json
common/package.json
server/package-lock.json
server/package.json

- update zod version to latest in client, server and common types
- fix vulnerabilities in few packages in server and client
Closes #944

update zod package version

---

client/index.html

Check browser version and give dismissible alert if browser not firefox or chromium based (Noticed weird behavior on Safari which needs fixing). For now this warning guides user to try the supported browsers.

check and alert for unsupported browser

---

client/package-lock.json
client/package.json
client/src/components/StaticPageView.tsx
client/src/components/front-page/SisuCourseDialog.tsx
client/src/components/front-page/SisuInstance.tsx
common/types/sisu.ts
server/package-lock.json

- Some Sisu searches fail due to null or undefined fields returned from Sisu, set these as optional in zod schema
- Update vulnerable npm packages, dependabot failed fixing these

More lax sisu parse

---

client/src/context/GradesTableProvider.tsx

The dynamic grade cells will now be grouped by the grade they are showing

Fix Grouping based on grade

---

client/src/components/course/course-results-view/GradesTableToolbar.tsx
e2e-tests/tests/admin.spec.ts
e2e-tests/tests/common/grades.ts
e2e-tests/tests/teacher.spec.ts

Filter grades table by name or student number

---

client/public/support.html
package.json

support email
