README.md
ssh.config

Note that this will require you to have configured the usernames for the corresponding hosts in your own SSH config (`~/.ssh/config`), e.g.
```
Host magi
User hannula7
Host grades
User hannula7
```
This port forwarding *should* only make the services available from your local machine (not even the local network beyond that), as long as you're careful with not forwarding them any further.

Add SSH config with help for forwarding ports from the dev server

---

.github/workflows/auto-merge.yml

Small amendments to the auto-merge action. Currently if a draft PR is created, the action will fail, which shouldn't have any effect on functionality, but GitHub will show that checks have failed when they practically have not.

Only run auto-merge job if PR is not a draft

---

server/src/database/migrations/00001-initial-migration.ts
server/src/database/models/user.ts

When writing some test code for Argon2id, I found that the ASCII representation of the hash could become much larger than the current 60, even up to 100 characters long. Let's make the DB field 255 characters long to be safe.

Bump up password storage size

---

server/src/database/seeders/001-dummy-data.ts

The previous mitigation to the issue with autoincrement indices not matching the expectations of the hardcoded seed data seemed to have an off-by-one error. This PR changes the seed:down script so that it deterministically resets the sequence numbers to their original values as per the opinion of Postgres.

Fix off-by-one error in seed:down

---

reuse-annotate.sh

`addheader` has been deprecated in favor of `annotate`.

REUSE fixes

---

client/Dockerfile
docker-compose.yaml
server/Dockerfile

Speed up Docker by performing chown as part of the COPY process, rather than through shell

Speed up Docker by performing chown as part of COPY

---

server/.eslintrc.json

Adds an ESLint rule to enforce avoiding (primarily) one-line if statements.
```ts
if (foo) bar();
else throw new Error();
```
will be corrected to:
```ts
if (foo)
bar();
else
throw new Error();
```
I would have included this in the refactoring PR but I only discovered this rule now.

Add nonblock statement ESLint rule

---

client/src/components/EditInstanceView.js
client/src/components/FetchInstancesView.js
client/src/components/auth/PrivateRoute.js
client/src/components/edit-instance-view/EditInstanceForm.js
client/src/components/fetch-instances-view/FetchedInstances.js
client/src/mock-data/mockSisuInstances.js
client/src/services/courses.js
client/src/services/instances.js
client/src/tests/EditInstance.test.js
client/src/tests/FetchInstances.test.js

Fixes needed to make the main functional again.
Note: I added the new ".data" to code located in the services folder for everything except the authentication related functionality. I think this is the easiest way to move forward with the least amount of changes to existing code. The auth code already worked with the new routes for the most part (outside the user service), so I decided to let it be. @kiiamakir decide if you want to change that.
And I'm now realising that the tests for fetch instances and edit instance probably fail because the mock data hasn't been changed to match the new route data.

Fixes to account for backend changes

---

server/src/controllers/course.ts
server/src/controllers/courseInstance.ts
server/src/controllers/utils/course.ts
server/src/routes/courseInstance.ts
server/test/controllers/courseInstance.test.ts

Adds a requirement to include course ID in the remaining course instance route which doesn't require it.
Ideally we would use composite keys, but there seemed to be problems with getting Sequelize to work with them cleanly. But that can be addressed later and hopefully without breaking the frontend connection after it has been fixed in this PR.

Include course ID in all course instance routes

---

docker-tests/docker-compose.yaml
server/Dockerfile

This re-enables coverage reporting, which has been plagued by permission problems for a while

Fix coverage reporting in server Dockerfile

---

server/src/controllers/auth.ts
server/src/controllers/courseInstance.ts

Rather than manually listing all enum members in Yup validation schemas, which is prone to breakage when adding new enum members, `Object.values` returns all of the enum values automatically.

Use Object.values for yup enum validation

---

server/src/database/index.ts

2 changes to the sequelize setup.
* Set `dialectsOption` ssl conditional, if running in production environment, require that ssl is set up, otherwise ignore (development and test environments work the same way as before).
* Enable sequelize (query) logging only when `NODE_ENV` is "development", this way no unnecessary clutter in the terminal when running tests.

update sequelize setup

---

client/src/components/CreateAssignmentView.js
client/src/components/create-assignment/LeafAssignment.js
client/src/components/create-assignment/ParentAssignment.js
client/src/components/create-assignment/StringTextField.js
client/src/components/formula-attributes-view/Assignment.js
client/src/components/formula-attributes-view/FormulaAttributesForm.js
client/src/components/select-formula-view/SelectFormulaForm.js
client/src/mock-data/mockAttainmentsClient.js
client/src/mock-data/mockFormulas.js
client/src/services/assignments.js
client/src/services/formulas.js
client/src/tests/CreateAssignmentView.test.js
client/src/tests/EditAssignmentView.test.js

Frontend code refactored so that attainments now list the formula attributes as objects instead of an array. This was done to match the implementation in backend. In order for the code to work, the backend should return a list of attributes that match the keys in the attainments' attribute object.
An example:
An attainment that uses the formula x lists the attributes as an object
formulaAttributes: {
maxPoints: "10",
minRequiredPoints: "5",
weight: "0.5"
}
Formula x includes the same keys in an array
["maxPoints", "minRequiredPoints", "weight"]

Frontend refactor of formula attributes

---

server/src/app.ts
server/test/controllers/general.test.ts

Replace default Express 404 html page with one that is more inline with APIs error messages.
example for GET /v1/course/all
```json
{
"success": false,
"errors": [
"Cannot GET /v1/course/all. Please refer to the API documentation at https://aalto-grades.cs.aalto.fi/api-docs/ for a list of available endpoints."
]
}
```

404 endpoint

---

client/src/App.tsx
client/src/components/CourseView.tsx
client/src/components/auth/PrivateRoute.tsx
client/src/components/course-view/CourseDetails.tsx
client/src/context/AuthProvider.tsx

Check on course view if the logged in user is in the teachers in charge, render the course view based on this information. Save the value also in auth context so it can be easily accessed when creating new instances for the course. Value updates every time new course is opened.
related to #228

Conditional render course view for teacher in charge

---

server/src/controllers/attainment.ts
server/src/routes/assessmentModel.ts
server/src/routes/attainment.ts
server/src/routes/courseInstance.ts
server/test/controllers/attainment.test.ts
server/test/mock-data/attainment.ts

Restrict attainment add/edit/delete related API endpoints to admin and teacher in charge users.
related to #228

Restrict attainment creation/add/delete rights

---

client/src/components/EditInstanceView.tsx
client/src/components/FetchInstancesView.tsx
client/src/components/edit-instance-view/EditInstanceForm.tsx
client/src/components/fetch-instances-view/FetchedInstances.tsx
common/types/course.ts
server/src/controllers/courseInstance.ts
server/src/controllers/sisu.ts
server/src/routes/courseInstance.ts
server/test/controllers/courseInstance.test.ts
server/test/controllers/sisu.test.ts

* Disable selection for sisu instances which have already been assigned to courses.
* From sisu endpoints, return information whether or not sisu instance id is already assigned to instance
* Check on instance creation that sisu id is available, throw error if not
* Return Sisu API error code in error response to client
closes #265 
closes #206

Attempting to add course instance with an existing Sisu instance ID

---

server/package-lock.json
server/package.json
server/src/app.ts

HelmetJs with default configuration. Mitigates risk for XSS among other things.
related to #371

Helmet ExpressJS middleware

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.reuse/dep5

GitHub does not recognize the issue templates with the license notice header, and if it is placed lower in the files, it will also appear in every issue being created with the templates.

Fix issue templates

---

common-services.yaml
docker-compose-from-images.yaml
reverse-proxy/reverse-proxy.conf
server/docker-compose.yaml

Contains needed changes to docker-compose-from-images.yaml and reverse proxy configurations to make pgAdmin available at aalto-grades.cs.aalto.fi.
Closes #449

Make pgAdmin available also in deployment environment

---

common/types/course.ts
common/types/general.ts
common/types/grades.ts
common/types/index.ts
server/src/controllers/courseInstance.ts
server/src/controllers/grades.ts
server/src/controllers/utils/date.ts
server/src/database/migrations/00004-update-attainment-grade-dates-to-dateonly.ts
server/src/database/models/attainmentGrade.ts
server/src/database/models/courseInstance.ts
server/src/routes/courseInstance.ts
server/src/routes/grades.ts
server/test/controllers/courseInstance.test.ts
server/test/controllers/grades.test.ts

Updates date and expiry date in the attainment grade table to the `DATEONLY` type and makes these as well as course instance starting and ending dates explicitly get returned from the API in a `YYYY-MM-DD` format.
Closes #474

Date format in API and database

---

client/src/components/course-results-view/SisuDownloadDialog.tsx
server/src/routes/grades.ts

Enable downloading Sisu CSV with only unexported, already exported or all grades selected.
Closes #429

Multiple sisu export CSV

---

client/src/components/EditAttainmentView.tsx

Set the cache time to 0 on edit attainment view to make sure latest attainment data is fetched from backend.
Closes #390

disable cache to always fetch latest attainment data

---

client/src/components/EditAttainmentView.tsx
client/src/components/EditCourseView.tsx
client/src/components/EditInstanceView.tsx
client/src/components/edit-attainment-view/Attainment.tsx
client/src/components/edit-attainment-view/LeafAttainment.tsx
client/src/components/edit-attainment-view/ParentAttainment.tsx
client/src/components/edit-attainment-view/SimpleDialog.tsx

Added initial values to edit forms and correctly compared them to determine if the form has been edited.
Closes #483

Fixed edit form unsaved changes dialog

---

client/src/components/course-results-view/CourseResultsTableToolbar.tsx
client/src/components/course-results-view/SisuDownloadDialog.tsx

Fixed abrupt change in dialog caused by refetch by adding the refetch to the onExited callback of the dialog transition
Related to #496

Fix: abrupt change in dialog caused by refetch

---

common/types/grades.ts
server/docs/grades.yaml
server/src/controllers/grades.ts
server/src/routes/grades.ts
server/test/controllers/grades.test.ts

This pull request adds a new endpoint to the API that allows retrieving the grade tree of all users for a given course and assessment model. The endpoint is located at `/v1/courses/:courseId/assessment-models/:assessmentModelId/grades/fullTree`. 
[x] Test added

Add endpoint to get grade tree of all users

---

docker-compose-from-images-test.yaml
docker-compose-from-images.yaml
server/Dockerfile.prod.test

Mount the keys folder as a volume to production docker containers
\-
\-

Mount keys as volumes to prod docker containers

---

reverse-proxy/reverse-proxy.conf

One line fix in nginx config to get the real remote user ip in application http requests
Closes #619

fix nginx conf set forwarded for

---

client/src/hooks/api/finalGrade.ts
client/src/tests/mock-data/server.ts
server/docs/finalGrades.yaml
server/src/routes/finalGrades.ts
server/test/controllers/finalGrades.test.ts

Changes `finalGrade` to `final-grade` in the backend API to be more consistent with other API names.
None relevant.
Closes #657

Consistent API naming

---

common/types/aplus.ts
server/docs/aplus.yaml
server/src/controllers/aplus.ts
server/src/routes/aplus.ts
server/test/controllers/aplus.test.ts

Adds an endpoint for fetching a list of courses the requester is staff in, so that information about the courses' exercises can be fetched and grade sources can be added to attainments.
None.

A+ course list

---

server/docs/aplus.yaml
server/src/controllers/aplus.ts
server/test/controllers/aplus.test.ts

Deals with the case that the user has no staff courses in A+ by returning 404.
None.

404 when user has no A+ staff courses

---

client/src/components/course-view/SelectAplusGradeSources.tsx
common/types/aplus.ts
server/docs/aplus.yaml
server/src/controllers/aplus.ts
server/src/database/migrations/00013-add-aplus-grade-source-info.ts
server/src/database/models/aplusGradeSource.ts
server/test/controllers/aplus.test.ts
server/test/util/createData.ts

Replaces the `aplusCourseId` field in `AplusGradeSource` with a JSON `aplusCourse` field storing `AplusCourseData` objects and adds a `moduleName` field for module sources. Later, rather than a JSON field, we may want to store the course data as either individual fields or as its own table since multiple grade sources can and will reference the same A+ course, resulting in duplicate data.
Closes #693

Add A+ source info

---

client/vite.config.ts

Does it make sense to remove at least the console.log in production?

remove console.log

---

client/src/components/course-view/AddAplusGradeSourceDialog.tsx
client/src/components/course-view/CoursePartsView.tsx
client/src/components/course-view/CreateAplusCourseParts.tsx
client/src/components/course-view/NewAplusCoursePartsDialog.tsx
client/src/components/course-view/SelectAplusGradeSource.tsx
client/src/components/course-view/SelectAplusGradeSources.tsx
client/src/components/course-view/ViewAplusGradeSourcesDialog.tsx
client/src/hooks/api/aplus.ts
common/types/aplus.ts
server/docs/aplus.yaml
server/docs/common.yaml
server/docs/coursePart.yaml
server/src/controllers/aplus.ts
server/src/controllers/grades.ts
server/src/controllers/utils/aplus.ts
server/src/controllers/utils/coursePart.ts
server/src/routes/aplus.ts
server/test/controllers/aplus.test.ts
server/test/util/createData.ts

Adds an API endpoint to delete A+ grade sources and allows deleting them from and adding new ones to existing course parts from the frontend.
https://github.com/aalto-grades/base-repository/wiki/Design-Guidelines) - confirmation is not asked when deleting a grade source
Closes #759

A+ grade source management

---

client/src/components/course-view/AddAplusGradeSourceDialog.tsx
client/src/components/course-view/CoursePartsView.tsx
client/src/components/course-view/SelectAplusGradeSource.tsx
client/src/components/course-view/SelectAplusGradeSources.tsx
client/src/utils/utils.ts
common/util/aplus.ts
server/src/controllers/aplus.ts

Disallows adding the same A+ grade source to the same course part twice from the client.
Fixes #768

Don't allow adding the same A+ grade source twice from the client

---

server/src/controllers/aplus.ts
server/test/controllers/aplus.test.ts

Updates the A+ grade fetching endpoint to fetch grades from all sources of the course parts. In the future, we may want to allow selecting which sources to fetch from, or teachers will have to delete sources that they don't care about anymore to not fetch from them.
Fixes #673

Fetch grades from multiple A+ sources

---

server/src/database/migrations/00019-change-aplus-grade-source-constraint.ts
server/src/database/models/aplusGradeSource.ts

We already have constraints in place preventing deleting course parts and A+ grade sources which have grades, but when they don't have grades I see no reason to prevent deleting course parts with sources.
Fixes #761

Allow deleting course parts with A+ sources

---

client/src/components/course/course-results-view/SisuDownloadDialog.tsx

If selected student list include exported ones, which means that the dialog won't close after users download CSV file, the text of button is changes from "Cancel" to "Close"

Change button text from 'Cancel' to 'Close' conditionally based on selected students

---

client/public/locales/en/translation.json
client/public/locales/fi/translation.json
client/public/locales/sv/translation.json
client/src/App.tsx
client/src/components/shared/LoginAgainButton.tsx
client/src/context/NotistackWrapper.tsx
client/src/hooks/api/axios.ts
client/src/types/index.ts

- Adding a button "Login again" in the snack bar when token expired. Clicking this button will open up a new window for login again and the window will close after user successfully logged in
- Preventing Snackbar showing duplicate message

Add login button to the token expired error message

---

client/src/hooks/api/axios.ts
server/src/middleware/authentication.ts
server/src/routes/aplus.ts
server/src/routes/auth.ts
server/src/routes/course.ts
server/src/routes/coursePart.ts
server/src/routes/courseTask.ts
server/src/routes/finalGrade.ts
server/src/routes/gradingModel.ts
server/src/routes/taskGrade.ts
server/src/routes/user.ts
server/test/util/responses.ts

- Backend: Create our own middleware for JWT authentication that still mainly use passportJs lib but added new callback to handle error messages
- Frontend: Modify axios interceptor to handle the error messages including the case that token expired

Create a new jwt authentication middleware to handle error message correctly

---

docker-compose-from-images-dev.yaml

- Add the depends_on property for the reverse proxy service in the dev file because the depends_on can not be extended.
- Update the interval of watch tower from 10 minutes to 1 hour

Fix auto recreate reverse proxy watch tower
